### ISSUE TITLE
Wayland?

### ISSUE THREAD

**Issue by Crehet** [4ndrs/PureMPV#2] opened 2022-12-30 02:19 UTC
tried it but nope.

**Comment by 4ndrs** [comment] 2022-12-30 12:53
I gave it a quick try on Ubuntu 22.10 with GNOME 43.1/Wayland, and after installing xclip with `sudo apt install xclip` the script copied the timestamps and path correctly to primary and clipboard. Currently, it doesn't show a warning or errors if xclip is not installed, and just prints the message that the string was copied (I need to change that). Which distro/setup are you using?

**Comment by Crehet** [comment] 2023-01-02 03:35
>Which distro/setup are you using?

archlinux kde wayland with [wl-clipboard](https://archlinux.org/packages/community/x86_64/wl-clipboard/)

**Comment by 4ndrs** [comment] 2023-01-02 08:15
Added support for wl-clipboard in 073e7c24686bcff66aab8656f681c725a8159bc5

**Comment by Crehet** [comment] 2023-01-03 05:08
forgive me my lord, i dunno how to troubleshoot stuff, so i can't really help you much besides telling you:
it didnt werk.
what exactly didnt werk? 
- copying timestamps to clipboard
- copying `ffmpeg -ss hh:mm:ss -to hh:mm:ss -i "/path/to/file" -lavfi crop=w:h:x:y` to clipboard


i've done as you stated in the readme:

```
cd ~/.config/mpv/scripts
git clone your_repo
main.js file is inside PureMPV and not out of it
```


btw, i refuse to install/use xclip, sorry.

**Comment by 4ndrs** [comment] 2023-01-03 05:31
It's okay, don't worry.
Support was added for wl-clipboard but the main.js in the repo gets updated only when there is a version bump. For the latest commit you can grab one of GitHub's automatic builds [here](https://github.com/4ndrs/PureMPV/releases/download/bleeding-edge/main.js).

The default selection is primary even for wl-clipboard, to change it set ```selection=clipboard``` in ```~/.config/mpv/script-opts/PureMPV.conf```

**Comment by Crehet** [comment] 2023-01-03 20:57
with the [latest main.js](https://github.com/4ndrs/PureMPV/releases/download/v0.1.1/main.js) copying to clipboard and primary clipboard didnt werk even with `slection=clipboard` in `~/.config/mpv/script-opts/PureMPV.conf`
with the [pre-release main.js](https://github.com/4ndrs/PureMPV/releases/download/bleeding-edge/main.js) copying to `clipboard` werks just fine, but if `selection=clipboard` isnt in `~/.config/mpv/script-opts/PureMPV.conf` copying to `primary clipboard`  doesnt werks

Cropping is extremely buggy and practically unusable

next part you can ignore it, it is only relevant if you know of [firejail](https://github.com/netblue30/firejail). 
with firejail; [PureWebM](https://github.com/4ndrs/PureWebM) werks fine if used in the cmdline. but if i try to use it via mpv  with `ctrl+o` it just doesnt werk even though i've whitelisted the appropriated folders in a custom firejail profile for purewebm like:

```
whitelist ${HOME}/.config/PureWebM
whitelist ${HOME}/.local/bin/purewebm
whitelist ${HOME}/.local/pipx
```
it just throws an error saying: `Error: no suitable /home/werks/.local/bin/purewebm`

if you want to know what i have for the custom purewebm profile, here is it:
````
# Persistent local customizations
quiet
include purewebm.local
# Persistent global definitions
# added by included profile
#include globals.local
# Python 3
ignore blacklist ${PATH}/python3*
ignore blacklist ${PATH}/python3*
ignore blacklist /usr/include/python3*
ignore blacklist /usr/lib/python3*
ignore blacklist /usr/lib64/python3*
ignore blacklist /usr/local/lib/python3*
ignore blacklist /usr/share/python3*
# Python 2
#ignore blacklist ${PATH}/python2*
#ignore blacklist /usr/include/python2*
#ignore blacklist /usr/lib/python2*
#ignore blacklist /usr/local/lib/python2*
#ignore blacklist /usr/share/python2*

noblacklist ${VIDEOS}
noblacklist ${HOME}/.config/PureWebM
noblacklist ${HOME}/.local/bin/purewebm
noblacklist ${HOME}/.local/pipx

include disable-common.inc
include disable-devel.inc
include disable-interpreters.inc
include disable-programs.inc
include disable-xdg.inc
include disable-X11.inc

whitelist ${VIDEOS}
whitelist ${HOME}/.config/PureWebM
whitelist ${HOME}/.local/bin/purewebm
whitelist ${HOME}/.local/pipx

apparmor
caps.drop all
machine-id
netfilter
net none
nogroups
nonewprivs
noroot
nou2f
protocol unix,inet,inet6
seccomp
seccomp.block-secondary
tracelog

private-bin purewebm,env,ffmpeg,python*,mpv
private-cache
private-etc alternatives,ld.so.cache,ld.so.preload

dbus-user none
dbus-system none

# Redirect
#include youtube-dl.profile
````

**Comment by 4ndrs** [comment] 2023-01-04 06:31
> copying to `clipboard` werks just fine, but if `selection=clipboard` isnt in `~/.config/mpv/script-opts/PureMPV.conf` copying to `primary clipboard` doesnt werks

Strange. I tried both on Ubuntu/gnome, and Arch/KDE with wl-clipboard and they copied the strings as instructed to the primary selection. Only KDE had an issue where the <kbd>shift</kbd> + <kbd>insert</kbd> didn't paste what it copied to primary, but middle mouse did work. You can try it out executing ```echo -n hello | wl-copy --primary``` in your terminal and see if it works or not directly.

> Cropping is extremely buggy and practically unusable


Yeah, it really was. It was terrible, and was what prompted me to make PureBox. I didn't know at the time how to draw the box on mpv apart from using ffmpeg filters which was extremely heavy, and didn't work with hwdec. I just fixed the internal cropbox with these two commits: b7460e50f050b81277433192e16c63b6ea6f609c and b11000092aa92b7a4eb168b14b0052c2bfb854d3. It uses ass-events now, which is much faster and works with hwdec.

**Comment by Crehet** [comment] 2023-01-04 20:29
<kbd>shift</kbd> + <kbd>insert</kbd> is not werking for me aswell
>`echo -n hello | wl-copy --primary`

yeah, no problems with that, it werks. well, i may have confused the files a some point the _main.js_ files and the firejail config.
copying to primary clipboard without `selection=clipboard` in `PureMPV.conf` werks fine now.
except  for <kbd>shift</kbd>+<kbd>insert</kbd>, well the <kbd>shift</kbd>+<kbd>insert</kbd> is likely an arch/kde/wl-clipboard issue

and cropping is now working as expected

**Comment by 4ndrs** [comment] 2023-06-14 13:17
Closing this issue since now I'm using a linux box with Wayland and can confirm support is working as intended. Thank you for the feedback Crehet.

**Closed as completed by 4ndrs** 2023-06-14 13:17 UTC
